version: '3'

services:
  php:
    # image: php:7.2-apache
    build: ./php
    volumes:
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./html:/var/www/html
    ports:
      - 8080:80
    container_name: php7.2
  mysql :
    image: mysql:5.7.23
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./mysql:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    restart: always
    environment:
      COMPOSE_PROJECT_NAME: sampe 
      MYSQL_ROOT_PASSWORD: passw0rd
      MYSQL_USER: "example_user"
      MYSQL_PASSWORD: "example_pass"
      MYSQL_DATABASE: "example_schema"
      # - COMPOSE_PROJECT_NAME
      # - MYSQL_ROOT_PASSWORD=root
      # - MYSQL_USER="example_user"
      # - MYSQL_PASSWORD="example_pass"
      # - MYSQL_DATABASE="sample_ueda_db"
      # - MYSQL_DATABASE=test2
    # container_name: mysqldatabase
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=example_user
      - PMA_PASSWORD=example_pass
    links:
      - mysql
    ports:
      - 4040:80
    volumes:
      - ./phpmyadmin/sessions:/sessions